services:
  langchain4j:
    build:
      context: .
    env_file:
      - .env
    environment:
      APPLICATION_MCP_URL: http://mcp-server:8080/sse
    ports:
      - "8080:8080"
    depends_on:
      - mcp-server
  mcp-server:
    build:
      context: github-mcp-server
    env_file:
      - .env
    command:
      - --pass-environment
      - --sse-port=8080
      - --sse-host=0.0.0.0
      - --
      - /opt/github-mcp-server
      - --toolsets
      - all
      - stdio
